version: '3.8'
services:
  postgres:
    image: postgres:15.5
    container_name: yams_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - yams_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: yams_backend
    ports:
      - "${PORT}:3000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - PORT=${PORT}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - yams_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: yams_frontend
    ports:
      - "19006:19006"
      - "8081:8081"
    volumes:
      - ./app:/app/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
      - EXPO_USE_DEV_SERVER=true
      - WATCHPACK_POLLING=true
      - EXPO_WEBPACK_BUNDLES=true
    networks:
      - yams_network
    depends_on:
      - backend

networks:
  yams_network:
    driver: bridge

volumes:
  postgres_data: 